site_name: IHC 2023.1

repo_name: "2023.1 grupo 2"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Grupo02"

copyright: "Copyright &copy; 2023 ihc"

theme:
  name: material
nav:
  - Home: index.md
  - Atas:
      - 01/04/2023: atas/ata_01_04.md
  - Planejamento:
      - Cronograma planejado: planejamento/cronogramaPlanejado.md
      - Ferramentas: planejamento/ferramentas.md    
