site_name: Wikipedia

repo_name: "Wikipedia"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Wikipedia"

copyright: "Copyright &copy; 2023 Wikipedia"

theme:
  name: material
  language: pt-BR
  favicon: images/wikipedia.png

  palette:
    - scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro
  
  icon:
    repo: fontawesome/brands/github
    
  logo: images/wikipedia.png

nav:
  - Home: index.md
  - Atas:
      - 01/04/2023: atas/ata_01_04.md  
      - 07/04/2023: atas/ata_07_04.md
      - 21/04/2023: atas/ata_21_04.md
      - 05/05/2023: atas/ata_05_05.md
      - 19/05/2023: atas/ata_19_05.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentacao 4: apresentacoes/apresentacao4.md
      - Apresentacao 5: apresentacoes/apresentacao5.md
  - Politicas:
      - Metodologias: politicas/metodologias.md
      - Issues: politicas/issues.md
      - Pull requests: politicas/pullrequest.md
      - Commit: politicas/commit.md
      - Branch: politicas/branch.md
  - Planejamento:
      - Cronogramas: 
        - Planejado: planejamento/cronogramaPlanejado.md
        - Realizado: planejamento/cronogramaRealizado.md
      - Sites analisados: planejamento/sitesAnalisados.md
      - Site selecionado:
        - Sobre a Wikipedia: planejamento/siteEscolhido.md    
        - Avaliação Heurística: planejamento/avaliacaoHeuristica.md  
      - Ferramentas: planejamento/ferramentas.md
      - Disponibildade dos Membros: planejamento/disponibilidade.md   
      - Processo de Design: planejamento/processo.md
  - Análise de Requisitos:
      - Perfil de Usuário: analise-de-requisitos/perfilDeUsuario.md 
      - Personas: analise-de-requisitos/personas.md
      - Aspectos éticos: analise-de-requisitos/aspectosEticos.md
      - Análise de Tarefas:
        - AHT: analise-de-requisitos/aht.md
        - GOMS: analise-de-requisitos/goms.md
      - Princípios Gerais do Projeto: analise-de-requisitos/principiosGerais.md
      - Características da Plataforma: analise-de-requisitos/caracteristicaDaPlataforma.md
      - Guia de estilo: analise-de-requisitos/guiaDeEstilo.md
      - Metas de Usabilidade: analise-de-requisitos/metasUsabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
        - Storyboard:
          - Planejamento da avaliação: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoDaAvaliacao.md
          - Planejamento do relato: design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoResultadosAvaliacaoStoryboard.md
          - Relato dos resultados: design-avaliacao-desenvolvimento/nivel1/storyboard/relatoDosResultadosStoryBoard.md
        - Análise de tarefas:
          - Planejamento da avaliação: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/planejamentoDaAvaliacaoTarefas.md
          - Planejamento do relato: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/planejamentoResultadosAnalisesTarefas.md
          - Relato dos resultados: design-avaliacao-desenvolvimento/nivel1/analiseDeTarefas/relatoDaAnaliseDeTarefa.md

      - Nível 2:
        - Protótipo de papel:
          - Planejamento da Avaliação: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/planejamentoDaAvaliacaoPrototipoDePapel.md
          - Planejamento do relato: design-avaliacao-desenvolvimento/nivel2/prototipoDePapel/planejamentoRelatoResultadosAvaliacaoPrototipoPapel.md

