site_name: Wikipedia

repo_name: "Wikipedia"
repo_url: "https://github.com/Interacao-Humano-Computador/2023.1-Wikipedia"

copyright: "Copyright &copy; 2023 Wikipedia"

theme:
  name: material
  language: pt-BR
  favicon: images/wikipedia.png

  palette: 
    - scheme: default
      primary: black
      accent: blue
  
  icon:
    repo: fontawesome/brands/github
    
  logo: images/wikipedia.png

nav:
  - Home: index.md
  - Atas:
      - 01/04/2023: atas/ata_01_04.md  
      - 07/04/2023: atas/ata_07_04.md
  - Planejamento:
      - Cronograma planejado: planejamento/cronogramaPlanejado.md
      - Ferramentas: planejamento/ferramentas.md    
